'use strict';
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const api=require('../static/sidebar-cache.js');
assert.deepEqual(api.clean(['民法','民法','数学']),['民法','数学']);
for(const invalid of [null,{},[1],[''],['x'.repeat(81)]])assert.equal(api.clean(invalid),null);
assert.equal(api.read({getItem(){return '{broken';}}),null);
assert.equal(api.read({getItem(){throw Error('blocked');}}),null);
assert.doesNotThrow(()=>api.write({setItem(){throw Error('quota');}},['民法']));
const names=['民法','<b>数学</b>'];
const container={dataset:{},replaceChildren(...nodes){this.nodes=nodes;}};
const context={window:{localStorage:{getItem(){return JSON.stringify(names);}},location:{search:'?subject='+encodeURIComponent('民法')}},URLSearchParams,document:{createElement(){return {classList:{add(){}},dataset:{},append(...children){this.children=[...(this.children||[]),...children];},setAttribute(k,v){this[k]=v;}};}}};
vm.runInNewContext(fs.readFileSync(require.resolve('../static/sidebar-cache.js'),'utf8'),context);
context.window.ClassroomSubjects.mount(container);
assert.equal(container.nodes.length,3);
assert.equal(container.nodes[1].children[0]['aria-current'],'true');
assert.equal(container.nodes[2].children[0].textContent,'<b>数学</b>');
assert.equal(container.nodes[2].children[0].href,'/library?subject='+encodeURIComponent('<b>数学</b>'));
assert.equal(container.dataset.subjectSignature,JSON.stringify(names));
console.log('Sidebar snapshot tests passed: synchronous render, selected subject, safe text, invalid/blocked storage.');
